name: military_hub
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.5.2 <3.0.0'

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  dynamic_theme: ^1.0.0
  swipedetector: ^1.2.0
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.2
  flutter_emoji: ">= 2.0.0"
  image_picker: ^0.6.7+2
  get_it: ^4.0.1
  flutter_bloc: ^3.2.0
  dio: 3.0.9
  photo_view: ^0.9.2
  google_maps_flutter: ^0.5.25+3
  uuid: ^2.1.0
  google_map_location_picker:
    path: ./plugins/google_map_location_picker
  janus_client: ^0.0.1
  flutter_webrtc: ^0.2.8
  permission_handler: ^5.0.1
  data_connection_checker: ^0.3.4
  dartz: ^0.8.9
  flutter_easyrefresh: ^2.1.1
  flui: ^0.9.2
  flutter_google_maps: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.2
  retrofit_generator: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo_military_hub.png
    - assets/img/logo_military_hub_l.png
    - assets/img/logo_military_hub_s.png

  fonts:
    - family: Staatliches
      fonts:
        - asset: assets/font/Staatliches-Regular.ttf
          weight: 100